tap "bufbuild/buf"
tap "homebrew/bundle"
tap "homebrew/core"
# GNOME XML library
brew "libxml2"
# Windows XML Event Log parser
brew "evtx"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
