scheme: "Aquamarine Gold Soft Dark"
author: "kaptcha0"
base00: "101818" # soft dark teal background
base01: "182222"
base02: "223030"
base03: "4c5858"
base04: "9aa2a2"
base05: "d0cdc4" # warm beige text
base06: "e0ddd3"
base07: "ebe7df"
base08: "d87474" # soft coral
base09: "c99a60" # muted gold-orange
base0A: "e6cc8f" # golden sand
base0B: "6dbb8a" # mint green
base0C: "63c9c4" # aquamarine
base0D: "5ea6d0" # gentle sky blue
base0E: "a98bb8" # muted orchid
base0F: "bca57c" # warm golden beige
