scheme: "Aquamarine Gold Soft Light"
author: "kaptcha0"
base00: "f0ece4" # cream background
base01: "e4e0d6"
base02: "d5d2c9"
base03: "aeb6b6"
base04: "7c8888"
base05: "384444" # softened text (not pure black)
base06: "243030"
base07: "182222"
base08: "c65e5e" # softer coral red
base09: "b88a52" # warm muted orange
base0A: "d8bb72" # sandy gold
base0B: "5ca87a" # calm mint
base0C: "54bdb8" # aquamarine highlight
base0D: "4a94c2" # mid sky blue
base0E: "9879a9" # gentle orchid
base0F: "a88f68" # golden beige
