tap "homebrew/bundle"
tap "homebrew/core"
brew "libxml2"
brew "exa"
brew "fd"
brew "fzf"
brew "libavif"
brew "gd"
brew "graphviz"
brew "htop"
brew "lazydocker"
brew "lazygit"
brew "neovim", args: ["HEAD"]
brew "neovide"
brew "nvm"
brew "pnpm"
brew "radare2", args: ["HEAD"]
brew "ripgrep"
brew "starship"
brew "viddy"
