alias cbcopy="xclip -selection clipboard"
alias cbpaste="xclip -selection clipboard -o"
alias cp="cp -i"
alias docker-compose="docker compose"
alias esudo="sudo env \"PATH=$PATH\""
alias ls="eza -lag --header --icons"
alias md="mkdir -p"
alias open="xdg-open"
alias rm="rm -i"
alias watch="viddy"
alias which="command -v"

alias bettercap="esudo bettercap"
alias wireshark="esudo wireshark"
