alias cbcopy="xclip -selection clipboard"
alias cbpaste="xclip -selection clipboard -o"
alias cp="cp -i"
alias docker-compose="docker compose"
alias esudo="sudo --preserve-env=PATH env"
alias ls="exa -lag --header --icons"
alias md="mkdir -p"
alias open="xdg-open"
alias rm="rm -i"
alias vim="nvim"
alias watch="viddy"
alias which="command -v"

alias bettercap="esudo bettercap"
alias wireshark="esudo wireshark"
